# Site settings
title: Xin Meng
author: Xin Meng
email: xin.meng@anu.edu.au
description: "Xin Meng is a Professor of Economics at the College of Business and Economics, Australian National University."
keywords: "economics, professor, ANU, Xin Meng, Australian National University"
baseurl: / 
url: "https://staging.xinmenganu.net/" 


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
  - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  sass_dir: /assets/sass
  style: :compressed

timezone: Australia/Sydney
google_analytics: G-R4PHHMRLBR
